#!/usr/bin/python3
#
# Generated by ChatGPT
# Checked by Martin Molema
#


import ldap
import base64
import os

# LDAP server en bind instellingen
LDAP_SERVER="ldap://localhost"
BIND_DN="cn=admin,dc=NHLStenden,dc=com"
BIND_PW="test12345!"
BASE_DN="dc=NHLStenden,dc=com"

# Directory waar de afbeeldingen zijn opgeslagen
IMAGE_DIR="./avatars"

# Verbind met de LDAP-server
ldap_conn = ldap.initialize(LDAP_SERVER)
ldap_conn.simple_bind_s(BIND_DN, BIND_PW)

# Zoek alle InetOrgPerson accounts
search_filter = "(objectClass=inetOrgPerson)"
result = ldap_conn.search_s(BASE_DN, ldap.SCOPE_SUBTREE, search_filter, ["dn"])

# Teller voor de afbeeldingen
counter = 1

# Loop door alle gevonden accounts
for dn, _ in result:
    # Formatteer het volgnummer met drie cijfers
    image_number = f"{counter:03d}"
    image_file = os.path.join(IMAGE_DIR, f"{image_number}.jpeg")

    # Controleer of de afbeelding bestaat
    try:
        with open(image_file, "rb") as img_file:
            base64_image = base64.b64encode(img_file.read()).decode('utf-8')

        # Maak een LDIF wijziging voor de jpegPhoto attribuut
        mod_attrs = [(ldap.MOD_ADD, 'jpegPhoto', base64.b64decode(base64_image))]

        # Voer de wijziging uit
        ldap_conn.modify_s(dn, mod_attrs)

        print(f"Afbeelding {image_file} geüpload naar {dn}")

    except FileNotFoundError:
        print(f"Afbeelding {image_file} niet gevonden, overslaan...")

    # Verhoog de teller
    counter += 1

    # Stop als we 200 afbeeldingen hebben geüpload
    if counter > 200:
        break

# Sluit de verbinding met de LDAP-server
ldap_conn.unbind_s()